### ISSUE TITLE
Overview of seeds used?

### ISSUE THREAD

**Issue by 152334H** [facebookresearch/lingua#30]
Hi. I have noticed that in simple `main` training, there are (at least?) 3 kinds of seeds:
* `lingua.data.DataArgs` [seed](https://github.com/facebookresearch/lingua/blob/60af83693d8237397d65acd8e4eb6725dcc33bb7/lingua/data.py#L714)
* `apps.main.transformer.LMTransformerArgs` [seed](https://github.com/facebookresearch/lingua/blob/60af83693d8237397d65acd8e4eb6725dcc33bb7/apps/main/transformer.py#L65)
* `apps.main.train.TrainArgs` [seed](https://github.com/facebookresearch/lingua/blob/60af83693d8237397d65acd8e4eb6725dcc33bb7/apps/main/train.py#L80)

What is each seed responsible for? Is there a reasonable way to unify them?

**Comment by BadrYoubiIdrissi** [comment]
This is by design to seperate randomness of data linga.data.DataArgs from randomness of model init apps.main.transformer.LMTransformerArgs and the rest apps.main.train.TrainArgs. This makes for reproducible data loading and model init regardless of what happens elsewhere. So for instance you can completely change your model's architecture and you will still get exactly the same sequence of batches. You will quickly notice this in your loss curves as they will be very syncronised in the local variations
<img width="660" alt="image" src="https://github.com/user-attachments/assets/2d4ebe8f-cd46-46ec-a759-130d15dbc99f">
