### ISSUE TITLE
train.log is rank0 only but actual stdout is all ranks

### ISSUE THREAD

**Issue by 152334H** [facebookresearch/lingua#31]
title

see [here](https://github.com/facebookresearch/lingua/blob/main/lingua/logger.py#L122)

**Comment by BadrYoubiIdrissi** [comment]
This is by design so that on [slurm](https://github.com/facebookresearch/lingua/blob/60af83693d8237397d65acd8e4eb6725dcc33bb7/lingua/stool.py#L180-L184), logs of each rank get redirected to their own log file. We need logs from all ranks to debug issues but train.log is only meant as an overview of training.

**Comment by 152334H** [comment]
thanks for the detailed response! and apologies for adding noise to the issues page
