### ISSUE TITLE
A bit philosophical question: Why this instead of HF ecosystem around Trainer?

### ISSUE THREAD

**Issue by ViktorooReps** [facebookresearch/lingua#7]
First of all, thank you for releasing this library! I am excited to see future improvements both in functionality and documentation.

In its state right now, when do you see someone choosing lingua over HuggingFace ecosystem? What do you think the latter lacks that lingua can provide?

**Comment by SeunghyunSEO** [comment]
well, they are not comparable i guess.
hf trainer is not for pretraining or something.
it's not bad for end user to finetune open weight models.
but you cant pretrain llama3 with high MFU (not scalable) and probe (analysis on activations) it.
and hf trainer is not hackable to implement quickly (e.g. multi token predcition; mpt?) and integrate 3d, 4d parallelism because it is too abstract (ofc this is inevitable because they handle so many tasks and models related to all transformers of the world).
nowadays something like the Liger-kernel finally have  been implemented in hf trainer, but patching the triton kernel was originally very annoying.
this is why researchers need hackable codebase like lingua IMO.

**Comment by BadrYoubiIdrissi** [comment]
> well, they are not comparable i guess.
> hf trainer is not for pretraining or something.
> it's not bad for end user to finetune open weight models.
> but you cant pretrain llama3 with high MFU (not scalable) and probe (analysis on activations) it.
> and hf trainer is not hackable to implement quickly (e.g. multi token predcition; mpt?) and integrate 3d, 4d parallelism because it is too abstract (ofc this is inevitable because they handle so many tasks and models related to all transformers of the world).
> one more example, nowadays something like the Liger-kernel finally have  been implemented in hf trainer, but patching the triton kernel was originally very annoying.
> this is why researchers need hackable codebase like lingua IMO.

This sums it up very well ! This was born out of the need to have something hackable for one of our upcoming projects with @mathuvu. We wanted something where architecture and optimisations (fsdp/compile/tp) were separate so that quickly trying new ideas didn't require doing a huge refactor. Hopefully this will help people try crazier ideas that are still scalable all while having a good baseline to compare to!
